"""Postgres Row-Level Security for tenant isolation (plan §9, launch no-go gate).

Every table carrying org_id gets ENABLE + FORCE ROW LEVEL SECURITY and a policy
keyed to the request-scoped GUC `app.current_org_id`. FORCE means even the table
owner is subject to the policy. current_setting(..., true) returns NULL when the
GUC is unset, so an unscoped session sees ZERO rows — fail closed.

Vector and FTS queries inherit these policies automatically (OWASP LLM08 control):
there is no separate index-level filter to forget.

tests/test_rls_coverage.py fails CI if a new org-scoped table lacks a policy.
"""

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.db.base import Base
from app.db import models  # noqa: F401 — register all tables

POLICY_NAME = "tenant_isolation"

# organizations is scoped by its own id, not an org_id FK
_SELF_SCOPED = {"organizations": "id"}


def org_scoped_tables() -> dict[str, str]:
    """{table_name: tenant_column} for every table that must carry a policy."""
    scoped: dict[str, str] = {}
    for table in Base.metadata.tables.values():
        if table.name in _SELF_SCOPED:
            scoped[table.name] = _SELF_SCOPED[table.name]
        elif "org_id" in table.columns:
            scoped[table.name] = "org_id"
    return scoped


def generate_rls_ddl() -> str:
    statements: list[str] = [
        "-- LedgerBrief tenant isolation (generated by app/db/rls.py)",
        "-- Apply with: python scripts/apply_rls.py --apply",
    ]
    for table, column in sorted(org_scoped_tables().items()):
        statements += [
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
            f"DROP POLICY IF EXISTS {POLICY_NAME} ON {table};",
            (
                f"CREATE POLICY {POLICY_NAME} ON {table} USING "
                f"({column} = current_setting('app.current_org_id', true)::uuid);"
            ),
        ]
    return "\n".join(statements) + "\n"


def set_org_context(db: Session, org_id: str) -> None:
    """Activate tenant scope for this session/transaction. Called per request once
    auth resolves the org (app/db/base.get_db); RLS policies key off this GUC."""
    db.execute(
        text("SELECT set_config('app.current_org_id', :org_id, false)"),
        {"org_id": str(org_id)},
    )
